server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://${cloudServerSlave2:localhost}:8782/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${cloudServerSlave1:localhost}
  server:
    enable-self-preservation: false